### ISSUE TITLE
Does not run on gnome-shell 3.6.2

### ISSUE THREAD

**Issue by pmknutsen** [nanorepublica/gnome-shell-stock-ticker#2]
Ran the build script, and files are copied into the `.local/share/gnome-shell/extensions/` but extension does not load on gnome-shell 3.6.2 (Ubuntu 12.10). In the Tweak tool, it says `Error loading extension`.

**Comment by nanorepublica** [comment]
Check out the lasted commit, this should now work in gnome-shell 3.6.2 :)

**Comment by pmknutsen** [comment]
Yes, it does load fine now. Thanks.
